@InfraMapper_HostAddress = http://localhost:5117

GET {{InfraMapper_HostAddress}}/api/tasks
Accept: application/json

###

GET {{InfraMapper_HostAddress}}/api/tasks/1
Accept: application/json

###

POST {{InfraMapper_HostAddress}}/api/tasks
Content-Type: application/json

{
  "name": "new task"
}

###

PUT {{InfraMapper_HostAddress}}/api/tasks/1
Content-Type: application/json

{
  "id": 1,
  "name": "renamed",
  "isCompleted": true
}

###

DELETE {{InfraMapper_HostAddress}}/api/tasks/1

###
